# Predefined names, VIPs and servers
predefined_managers = ["Marcia Chavito", "Jose Andre", "Augusta Cachinduco", "Joaquim Manuel", "Aguiar Julia", "Pires Hetaelva", "Tonisha Cristiane", "Juliana Lima", "Mauro Caianda", "Simão ", "Magda", "David Tenente", "Ariete", "Jose Alberto", "Lucas", "Antonio Capemba", "Gabriel Oliveira", "Luan", "Junior Paciencia", "Candido Coxi", "Iracena Vieira", "Kamille", "Alberto Muanha", "Kikas Manuel", "Fernandes Antonio", "Antonio Jesus Joao Saraiva", "Venancio Gomes", "Daniel Marcelino", "Renato Francisco", "Kuingo Sebastiao", "Ribeiro Filomeno", "Marcos Simiao", "Gomes Hermenio"]
predefined_servers = ["Qa_Burg1.4", "Live_Burg3.1", "Qa_Burg1.2", "Live_Burg3.2", "Qa_Burg1.3", "Live_Burg3.3", "Brazil_QA1.1", "Other"]
predefined_agents = [
    "Capemba Antonio",
    "Stanley Saraiva Marques Lucas",
    "Leite Cardoso Luan Victor",
    "Oliveira Gabriel",
    "Paciencia Junior",
    "Da Veiga Moniz Ariete Celeste",
    "Mbiavanga Jose Alberto",
    "Simão Gedeão",
    "David Tenente",
    "Magda Pontes Lima",
    "Jose Andre",
    "De Pina Serra Cristiane Tonisha",
    "Aguiar Julia íris Lima de",
    "Augusta Cachinduco",
    "Chavito Marcia De Carvalho",
    "Virgilio Joaquim Manuel",
    "Bumba Mauro Caianda",
    "Pires Hetaelva",
    "Juliana Lima",
    "Coxi Candido João",
    "Dos Santos Moreira Kamille",
    "Iracena Vieira",
    "Alberto Muanha",
    "Venancio Gomes",
    "Kikas Manuel",
    "Daniel Marcelino Paolo Quilombo",
    "Renato Francisco",
    "Toco Antonio Fernandes Ngaca",
    "António Jesus Joao Saraiva",
    "Gomes Hermenio",
    "Marcos Simião Maria",
    "Ribeiro Filomeno Victorino",
    "Kuingo Sebastião Vovi",
    "Nicolau Oliveira",
    "Moreira Sandra",
    "Ugenga Ana",
    "Lopes Jeoclides B Lourenço",
    "Sebastiao Jotino Adriano Quitembo",
    "Siro Vandeste Francisco De Lemos",
    "Campos Gomes Amanda",
    "Babela Joao Cristo",
    "Mello Frey Ramon",
    "Graciano Zarelli Vitor",
    "Cruz Moreira Sara Cristina",
    "Mazuze Mellanie", "Marcia Chavito", "Jose Andre", "Augusta Cachinduco", "Joaquim Manuel", "Aguiar Julia", "Pires Hetaelva", "Tonisha Cristiane", "Juliana Lima", "Mauro Caianda", "Simão ", "Magda", "David Tenente", "Ariete", "Jose Alberto", "Lucas", "Antonio Capemba", "Gabriel Oliveira", "Luan", "Junior Paciencia", "Candido Coxi", "Iracena Vieira", "Kamille", "Alberto Muanha", "Kikas Manuel", "Fernandes Antonio", "Antonio Jesus Joao Saraiva", "Venancio Gomes", "Daniel Marcelino", "Renato Francisco", "Kuingo Sebastiao", "Ribeiro Filomeno", "Marcos Simiao", "Gomes Hermenio"
]